name: Python package

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        flake8 . --count --max-complexity=10 --show-source --statistics --verbose
    - name: Test with pytest
      run: |
        pytest
    - name: Validate notebooks with nbconvert
      run: |
        jupyter nbconvert --execute --to html examples/*.ipynb --output-dir examples/.nbconvert_output
